#!/bin/bash

OPTION=$1
PACKAGE=$2

shift; shift;

DEPLOY_DIR=`dirname $0`
LAB616_DIR=${DEPLOY_DIR}/..
AWS_DIR=${LAB616_DIR}/aws
AWS_INSTANCES=${AWS_DIR}/.instance
TARGET_DIR=${LAB616_DIR}/runtime/${PACKAGE}
SOURCE_DIR=${DEPLOY_DIR}/packages/${PACKAGE}
BINARY_FILES=${SOURCE_DIR}/bin
PROFILE_FILES=${SOURCE_DIR}/profiles
SCRIPT_FILES=${SOURCE_DIR}/${PACKAGE}
TEMPLATES_DIR=${SOURCE_DIR}/templates
LOCAL_FILES=${TEMPLATES_DIR}/local

APR_NATIVE=${LAB616_DIR}/third_party/java/apr/platforms/
TOMCAT_NATIVE=${LAB616_DIR}/third_party/java/tomcat-native/platforms/
#NATIVE_FILES="${TOMCAT_NATIVE}/linux/lib/libtcnative*.so ${TOMCAT_NATIVE}/macosx/lib/libtcnative*.jnilib"
#NATIVE_FILES="${APR_NATIVE}/linux/lib/libapr-*.so ${APR_NATIVE}/macosx/lib/libapr-*.jnilib "${NATIVE_FILES}

NATIVE_FILES="${APR_NATIVE} ${TOMCAT_NATIVE}"

REMOTE_SCRIPT=${PACKAGE}


# Resolve host name
function dns {
	name=$1; shift;
	state=`cat ${AWS_INSTANCES}/$name | awk -F"|" '{print $1}'`
	if [[ "$state" == "RUNNING" ]]; then
	    host=`cat ${AWS_INSTANCES}/$name | awk -F"|" '{print $4}'`
	    echo $host
	else
	    echo "Not running: state=$state"
	    exit -1
	fi
}


# Execute remotely
function run_remote {
    REMOTE_HOST=`dns $1`
    REMOTE_USER=$2
    shift; shift;
    REMOTE_ID_FILE=${DEPLOY_DIR}/accounts/${REMOTE_USER}.id_dsa

    ssh -i ${REMOTE_ID_FILE} ${REMOTE_USER}@${REMOTE_HOST} $@
}

# Execute locally
function run_local {
    $@
}

function build_package {
    BinType=$1;
    MainClass=$2;
    MavenProjectName=$3
    if [ ! -d ${SOURCE_DIR} ]; then
	echo "Directory ${SOURCE_DIR} missing.  Creating."
	mkdir -p ${SOURCE_DIR}
	mkdir -p ${BINARY_FILES}
	mkdir -p ${PROFILE_FILES}
	mkdir -p ${TEMPLATES_DIR}
	mkdir -p ${LOCAL_FILES}
	echo "MainClass = ${MainClass}"
	if [[ "$MainClass" == "" ]]; then
	    sed 's/@MAIN_CLASS/JAR/g' ${DEPLOY_DIR}/template-${BinType}.sh > ${SOURCE_DIR}/${PACKAGE}	    
	else
	    eval sed 's/@MAIN_CLASS/${MainClass}/g' ${DEPLOY_DIR}/template-${BinType}.sh > ${SOURCE_DIR}/${PACKAGE}  
	fi

	chmod a+x ${SOURCE_DIR}/${PACKAGE}
	
	# From the bin directory
	if [[ "${MavenProjectName}" != "" ]]; then
	    pushd ${BINARY_FILES}
	    MavenProjectDir=../../../../${MavenProjectName}
	    if [ -d ${MavenProjectDir} ]; then
		echo "Creating link to maven built jar file in ${MavenProjectName}."
		ln -s ${MavenProjectDir}/target/${MavenProjectName}-1.0-SNAPSHOT-jar-with-dependencies.jar ${PACKAGE}.jar
		popd;
	    fi
	fi
    fi
}

echo "PACKAGE=${PACKAGE}, TARGET=${TARGET_DIR}"

case "${OPTION}" in 
--newserver)
    build_package server $@
;;
--newtool)
    build_package tool $@
;;
--stagelocal)
    if [ ! -d ${TARGET_DIR} ]; then
	echo "Directory ${TARGET_DIR} missing.  Creating."
	mkdir -p ${TARGET_DIR}
    fi

    # Copy the files over from the template directory
    cp -r ${BINARY_FILES} ${TARGET_DIR}
    cp -r ${PROFILE_FILES} ${TARGET_DIR}
    cp -r ${SCRIPT_FILES} ${TARGET_DIR}
    cp -r ${LOCAL_FILES} ${TARGET_DIR}
    for n in ${NATIVE_FILES}; do
	cp -r $n/* ${TARGET_DIR}/bin
    done
;;
--rsync)
   # Simple case of just copy from local source to remote machine.
   # This deployment simply uses rsync.
   INSTANCE=$1; shift;
   REMOTE_USER=$1; shift;
   REMOTE_ID_FILE=${DEPLOY_DIR}/accounts/${REMOTE_USER}.id_dsa
   REMOTE_HOST=`dns $INSTANCE`
   echo "HOST = $REMOTE_HOST, ID = $REMOTE_ID_FILE"
   pushd ${TARGET_DIR}
   SRC=`pwd`
   popd
   rsync -zav --delete --links --rsh="ssh -i ${REMOTE_ID_FILE}" ${SRC} ${REMOTE_USER}@${REMOTE_HOST}:/home/${REMOTE_USER}/runtime
;;
--git)
   # Normally this should be done over ssh and the deployed server will just
   # checkout a given branch from git repository for production.
;;
--console)
   # Start a console at the instance name
   INSTANCE=$1; shift;
   REMOTE_USER=lab616
   REMOTE_ID_FILE=${DEPLOY_DIR}/accounts/${REMOTE_USER}.id_dsa
   REMOTE_HOST=`dns $INSTANCE`
   echo "HOST = $REMOTE_HOST, ID = $REMOTE_ID_FILE"
   ssh -i ${REMOTE_ID_FILE} ${REMOTE_USER}@${REMOTE_HOST}
;;
--cp)
   # Copy
   INSTANCE=$1; shift;
   REMOTE_USER=lab616
   REMOTE_ID_FILE=${DEPLOY_DIR}/accounts/${REMOTE_USER}.id_dsa
   REMOTE_HOST=`dns $INSTANCE`
   echo "HOST = $REMOTE_HOST, ID = $REMOTE_ID_FILE"
   scp -i ${REMOTE_ID_FILE} $1 ${REMOTE_USER}@${REMOTE_HOST}:$2
;;
--setupssh)
   # Sets up ssh password-less login at the remote host
   INSTANCE=$1; shift;
   REMOTE_USER=$1; shift;
   REMOTE_ID_FILE=${DEPLOY_DIR}/accounts/${REMOTE_USER}.id_dsa
   REMOTE_HOST=`dns $INSTANCE`
   echo "HOST = $REMOTE_HOST, ID = $REMOTE_ID_FILE"
   scp -i ${REMOTE_ID_FILE} ${REMOTE_ID_FILE}.pub ${REMOTE_USER}@${REMOTE_HOST}:/home/${REMOTE_USER}/.ssh/authorized_keys
;;
--start)
   # Start remotely.
   PROFILE=$1; shift;
   INSTANCE=$1; shift;
   REMOTE_USER=$1; shift;
   run_remote ${INSTANCE} ${REMOTE_USER} /home/${REMOTE_USER}/runtime/${PACKAGE}/${REMOTE_SCRIPT} ${PROFILE} $@
;;
--stop)
   # Stop remote server.
   PROFILE=$1; shift;
   INSTANCE=$1; shift;
   REMOTE_USER=$1; shift;
   REMOTE_PID=${PACKAGE}.${PROFILE}.pid
   PID=`run_remote ${INSTANCE} ${REMOTE_USER} cat /home/${REMOTE_USER}/runtime/${PACKAGE}/${REMOTE_PID}`
   run_remote ${INSTANCE} ${REMOTE_USER} kill -s TERM ${PID}
;;
--viewlog)
   # View the remote log file.
   PROFILE=$1; shift;
   INSTANCE=$1; shift;
   REMOTE_USER=$1; shift;
   REMOTE_PID=${PACKAGE}.${PROFILE}.pid
   REMOTE_LOG=${PACKAGE}.${PROFILE}.log
   run_remote ${INSTANCE} ${REMOTE_USER} cat /home/${REMOTE_USER}/runtime/${PACKAGE}/${REMOTE_LOG}
;;
--taillog)
   # View the remote log file.
   PROFILE=$1; shift;
   INSTANCE=$1; shift;
   REMOTE_USER=lab616
   REMOTE_PID=${PACKAGE}.${PROFILE}.pid
   REMOTE_LOG=${PACKAGE}.${PROFILE}.log
   run_remote ${INSTANCE} ${REMOTE_USER} tail -f /home/${REMOTE_USER}/runtime/${PACKAGE}/${REMOTE_LOG}
;;
--exec)
   # Exec remotely.
   INSTANCE=$1; shift;
   REMOTE_USER=$1; shift;
   REMOTE_ID_FILE=${DEPLOY_DIR}/accounts/${REMOTE_USER}.id_dsa
   REMOTE_HOST=`dns $INSTANCE`
   echo "HOST = $REMOTE_HOST, ID = $REMOTE_ID_FILE"
   run_remote ${INSTANCE} ${REMOTE_USER} !@
;;
--startlocal)
   # Start remotely.
   PROFILE=$1; shift;
   REMOTE_USER=$1; shift;
   run_local /home/${REMOTE_USER}/runtime/${PACKAGE}/${REMOTE_SCRIPT} ${PROFILE} $@
;;
--stoplocal)
   # Stop remote server.
   PROFILE=$1; shift;
   REMOTE_USER=$1; shift;
   REMOTE_PID=${PACKAGE}.${PROFILE}.pid
   PID=`cat /home/${REMOTE_USER}/runtime/${PACKAGE}/${REMOTE_PID}`
   run_local kill -s TERM ${PID}
;;
--tunnel)
   # SSH tunnel
   INSTANCE=$1;
   REMOTE_PORT=$2
   LOCAL_PORT=$3
   REMOTE_USER=$4
   REMOTE_ID_FILE=${DEPLOY_DIR}/accounts/${REMOTE_USER}.id_dsa
   ssh -i ${REMOTE_ID_FILE} -L ${LOCAL_PORT}:localhost:${REMOTE_PORT} ${REMOTE_USER}@`dns ${INSTANCE}`
;;
esac

