#!/bin/bash

OPTION=$1
PACKAGE=$2
PROFILE=$3

shift; shift; shift;

TARGET_DIR=`dirname $0`/../runtime/${PACKAGE}
SOURCE_DIR=`dirname $0`/packages/${PACKAGE}
BINARY_FILES=${SOURCE_DIR}/bin
PROFILE_FILES=${SOURCE_DIR}/profiles
SCRIPT_FILES=${SOURCE_DIR}/${PACKAGE}.sh
TEMPLATES_DIR=${SOURCE_DIR}/templates
LOCAL_FILES=${TEMPLATES_DIR}/local
REMOTE_USER=lab616
REMOTE_ID_FILE=`dirname $0`/accounts/${REMOTE_USER}.id_dsa
REMOTE_HOST=dev.lab616.com
REMOTE_SCRIPT=${PACKAGE}.sh
REMOTE_LOG=${REMOTE_SCRIPT}.${PROFILE}.log
REMOTE_PID=${REMOTE_SCRIPT}.${PROFILE}.pid

# Execute remotely
function run_remote {
    ssh -i ${REMOTE_ID_FILE} ${REMOTE_USER}@${REMOTE_HOST} $@
}

echo "PACKAGE=${PACKAGE}, TARGET=${TARGET_DIR}"

case "${OPTION}" in 
--stagelocal)
    if [ ! -d ${TARGET_DIR} ]; then
	echo "Directory ${TARGET_DIR} missing.  Creating."
	mkdir -p ${TARGET_DIR}
    fi

    # Copy the files over from the template directory
    cp -r ${BINARY_FILES} ${TARGET_DIR}
    cp -r ${PROFILE_FILES} ${TARGET_DIR}
    cp -r ${SCRIPT_FILES} ${TARGET_DIR}
    cp -r ${LOCAL_FILES} ${TARGET_DIR}
;;
--rsync)
   # Simple case of just copy from local source to remote machine.
   # This deployment simply uses rsync.
   pushd ${TARGET_DIR}
   SRC=`pwd`
   popd
   rsync -zav --delete --links --rsh="ssh -i ${REMOTE_ID_FILE}" ${SRC} ${REMOTE_USER}@${REMOTE_HOST}:/home/${REMOTE_USER}/runtime
;;
--git)
   # Normally this should be done over ssh and the deployed server will just
   # checkout a given branch from git repository for production.
;;
--start)
   # Start remotely.
   run_remote /home/${REMOTE_USER}/runtime/${PACKAGE}/${REMOTE_SCRIPT} ${PROFILE} $@
;;
--stop)
   # Stop remote server.
   PID=`run_remote cat /home/${REMOTE_USER}/runtime/${PACKAGE}/${REMOTE_PID}`
   run_remote kill -9 ${PID}
;;
--viewlog)
   # View the remote log file.
   run_remote tail -f /home/${REMOTE_USER}/runtime/${PACKAGE}/${REMOTE_LOG}
;;
--tunnel)
   # SSH tunnel
   REMOTE_PORT=$1
   LOCAL_PORT=$2
   shift; shift;
   ssh -i ${REMOTE_ID_FILE} -L ${LOCAL_PORT}:localhost:${REMOTE_PORT} ${REMOTE_USER}@${REMOTE_HOST}
;;
esac

