
# Setting PATH for MacPython 2.5
# The orginal version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/Current/bin:${PATH}"
export PATH

##
# Your previous /Users/dchung/.bash_profile file was backed up as /Users/dchung/.bash_profile.macports-saved_2009-09-04_at_15:17:07
##

# MacPorts Installer addition on 2009-09-04_at_15:17:07: adding an appropriate PATH variable for use with MacPorts.
export PATH=/opt/local/bin:/opt/local/sbin:$PATH
# Finished adapting your PATH environment variable for use with MacPorts.


# MacPorts Installer addition on 2009-09-04_at_15:17:07: adding an appropriate MANPATH variable for use with MacPorts.
export MANPATH=/opt/local/share/man:$MANPATH
# Finished adapting your MANPATH environment variable for use with MacPorts.

export PATH=/usr/local/git/bin:$PATH
export JRUBY_HOME=/Users/dchung/lab616/third_party/jruby
export SCALA_HOME=/Users/dchung/lab616/third_party/scala
export JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/1.6/Home
export PATH=$JAVA_HOME/bin:$SCALA_HOME/bin:$JRUBY_HOME/bin:$PATH
export MAVEN_OPTS=-Xmx512m
