#!/bin/bash

# Environment variables to set for the development enviornment.

# Special JAVA_HOME for Mac OS X Leopard.
export JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/1.6/Home

export JRUBY_HOME=/Users/dchung/lab616/third_party/jruby
export SCALA_HOME=/Users/dchung/lab616/third_party/scala
export PATH=$JAVA_HOME/bin:$SCALA_HOME/bin:$JRUBY_HOME/bin:$PATH
export MAVEN_OPTS=-Xmx512m
